# Generated by Django 3.2.12 on 2023-12-25 02:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('MaTaiKhoan', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('HoVaTen', models.CharField(max_length=255)),
                ('SoDienThoai', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('LoaiTaiKhoan', models.IntegerField(choices=[(1, 'Lanh Dao'), (2, 'Truong Diem Giao Dich'), (3, 'Giao Dich Vien'), (4, 'Truong Diem Tap Ket'), (5, 'Tap Ket Vien')])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('MaKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('HoVaTen', models.CharField(max_length=255)),
                ('SoDienThoai', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiemGiaoDich',
            fields=[
                ('MaDiemGiaoDich', models.AutoField(primary_key=True, serialize=False)),
                ('TenDiaDiemGiaoDich', models.CharField(max_length=255)),
                ('DiaDiem', models.CharField(max_length=255)),
                ('Hotline', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiemTapKet',
            fields=[
                ('MaDiemTapKet', models.AutoField(primary_key=True, serialize=False)),
                ('TenDiemTapKet', models.CharField(max_length=255)),
                ('DiaDiem', models.CharField(max_length=255)),
                ('Hotline', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDonHang', models.AutoField(primary_key=True, serialize=False)),
                ('NgayGuiHang', models.DateTimeField(blank=True, null=True)),
                ('NgayNhanHang', models.DateTimeField(blank=True, null=True)),
                ('TrangThai', models.IntegerField(choices=[(1, 'Nguoi gui den diem giao dich'), (2, 'Diem giao dich den diem tap ket goc'), (3, 'Diem tap ket goc den dich'), (4, 'Diem tap ket goc den diem tap ket dich'), (5, 'Diem tap ket dich den nguoi nhan'), (6, 'Tra don hang'), (7, 'Giao dich thanh cong')])),
                ('LoaiHang', models.CharField(max_length=255)),
                ('KhoiLuong', models.CharField(max_length=255)),
                ('Tien', models.IntegerField()),
                ('MoTaDonHang', models.CharField(max_length=255)),
                ('HoVaTenNguoiNhan', models.CharField(max_length=255)),
                ('DiaChiNhanHang', models.CharField(max_length=255)),
                ('SoDienThoaiNguoiNhan', models.CharField(max_length=255)),
                ('DiaChiNguoiGui', models.CharField(max_length=255)),
                ('DiemTapKet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.diemtapket')),
                ('MaDiemGiaoDich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.diemgiaodich')),
                ('MaKhachHang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer')),
                ('MaTaiKhoan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diemgiaodich',
            name='MaDiemTapKet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.diemtapket'),
        ),
        migrations.AddField(
            model_name='account',
            name='MaDiemGiaoDich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.diemgiaodich'),
        ),
        migrations.AddField(
            model_name='account',
            name='MaDiemTapKet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.diemtapket'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
