# Generated by Django 4.2.7 on 2023-12-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20231217_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='First_Last_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='PhoneNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='Type_Account',
            field=models.IntegerField(choices=[(1, 'Lanh Dao'), (2, 'Truong Diem GD'), (3, 'Giao Dich Vien'), (4, 'NV Giao Hang'), (5, 'Truong Diem Tap Ket'), (6, 'Tap Ket Vien')], null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
