# Generated by Django 3.2.12 on 2023-12-23 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_donhang_mataikhoan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='MaDiemGiaoDich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.diemgiaodich'),
        ),
        migrations.AlterField(
            model_name='account',
            name='MaDiemTapKet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.diemtapket'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='MaTaiKhoan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
