# Generated by Django 3.2.12 on 2023-12-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20231223_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diemtapket',
            old_name='TenDiemtTapKet',
            new_name='TenDiemTapKet',
        ),
    ]
