# Generated by Django 3.2.12 on 2023-12-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20231223_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='MaKhachHang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer'),
        ),
    ]
