# Generated by Django 3.2.12 on 2023-12-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_donhang_makhachhang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='MaDiemDen',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='MaDiemXuatPhat',
        ),
        migrations.AddField(
            model_name='donhang',
            name='DiemTapKet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.diemtapket'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='MaDiemGiaoDich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.diemgiaodich'),
        ),
    ]
